### ISSUE TITLE
识别的内容，可以用简单的文本么

### ISSUE THREAD

**Issue by hongyinjie** [crazy0x/ABNF-Parser#1]
目前：grammarResult——讯飞离线语法的识别结果
我想做一个简单的语法分析， 可以不用依赖讯飞，能做些简单的语义理解。。。

另外，我刚在做这块研究， 能一起探讨么？ 
hongyinjie@163.com

**Comment by crazy0x** [comment]
@hongyinjie 你好，科大讯飞将语法与语义分离开了，其在线语义是将其语法的识别结果作为输入的，我这边只是把解析工作离线化，所以并不支持简单的文本。

如果不依赖讯飞，可能要将语法连同语义的算法部分也一并实现，不单是写个解析器这么简单。
